# Generated by Django 6.0.1 on 2026-01-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_favorite_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
